name: Build Angular Frontend

on:
  push:
    paths:
      - 'rover-mission-frontend/**'
      - '.github/workflows/build-angular.yml'
  pull_request:
    paths:
      - 'rover-mission-frontend/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.19.0'  

    - name: Install dependencies
      run: npm install
      working-directory: rover-mission-frontend

    - name: Build Angular app
      run: npm run build
      working-directory: rover-mission-frontend
