name: CI - Rover Mission Planner

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build & Test (.NET + Angular)
    runs-on: ubuntu-latest

    services:
      sqlserver:
        image: mcr.microsoft.com/mssql/server:2022-latest
        env:
          SA_PASSWORD: "Your_password123"
          ACCEPT_EULA: "Y"
        ports:
          - 1433:1433
        options: >-
          --health-cmd "exit 0"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore RoverMissionPlanner.sln

    - name: Build solution
      run: dotnet build RoverMissionPlanner.sln --configuration Release --no-restore

    - name: Run tests
      run: dotnet test RoverMissionPlanner.sln --no-build --verbosity normal

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install Angular CLI
      run: npm install -g @angular/cli

    - name: Install frontend dependencies
      working-directory: ./rover-mission-frontend
      run: npm install

    - name: Build frontend
      working-directory: ./rover-mission-frontend
      run: ng build --configuration=production
